Import('env')

env.PythonExtension('mapdatautils', ['mapdatautils.pyx'])
env.PythonExtension('noise', ['noise.pyx'])

objs = env.SharedObject(Glob("slatec/src/*.f"))
objs += env.PythonObject(['slatec.pyx'])
env.PythonExtension('slatec', objs, PYEXTLINK='$FORTRAN')

env.PythonExtension('wigner', ['wigner.pyx'], LIBS=['m'])


