Import('env')

env.PythonExtension('mapdatautils', ['mapdatautils.pyx'])
env.PythonExtension('noise', ['noise.pyx'])

# d1mach needs to be compiled without optimization!!
d1mach_env = env.Clone()
d1mach_env.Replace(FORTRANFLAGS=env['FORTRAN_FPU_DETECT_FLAGS'])

objs = env.SharedObject([x for x in Glob("slatec_src/src/*.f")
                         if x.name != 'd1mach.f'])
objs += d1mach_env.SharedObject('slatec_src/src/d1mach.f')

objs += env.PythonObject(['slatec.pyx'])
env.PythonExtension('slatec', objs, PYEXTLINK='$FORTRANPYEXTLINK')

env.PythonExtension('wigner', ['wigner.pyx'], LIBS=['m'])


